### ISSUE TITLE
nemo-preview not working

### ISSUE THREAD

**Issue by wujastyk** [linuxmint/nemo-extensions#246]
nemo-preview isn't working for me.  I'm using Linux Mint 18.3 with the new Cinnamon 3.6.2 from the Embrosyn PPA (nemo-preview is 3.6.0-1~xenial1).

I open Nemo, select a file, hit spacebar and ... nothing.

I imagine this is because I'm using a pre-release version and it will all fall into place with the official new release of Cinnamon.  I just thought I'd say.

Dominik

Setup:

LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:printing-9.20160110ubuntu0.2-amd64:printing-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya

**Comment by miczac** [comment]
just upgraded to 18.3 from 18.2. Worked no 18.2.
nemo-preview won't work either on Sylvia.
Also checked with a newly created user to make sure there isn't clutter involved.

**Comment by mtwebster** [comment]
Can you start nemo-preview from a terminal, then try to activate in nemo.  Paste any relevant output from it.

Thanks

**Comment by miczac** [comment]
it won't come that far:
`$ nemo-preview 

(nemo-preview-start:9976): Cjs-WARNING **: JS ERROR: Error: Requiring XreaderDocument, version none: Typelib file for namespace 'XreaderDocument' (any version) not found
@/usr/share/nemo-preview/js/viewers/evince.js:28:7

Segmentation fault
`

**Comment by leigh123linux** [comment]
I see the same error in F28 with the typelib installed

**Comment by mtwebster** [comment]
Can you guys run:

```
find /usr -name "XreaderDocument-1.5.0.*"
```

**Comment by leigh123linux** [comment]
```
$ find /usr -name "XreaderDocument-1.5.0.*"
/usr/lib64/girepository-1.0/XreaderDocument-1.5.0.typelib
```

**Comment by miczac** [comment]
```
# find /usr -name "XreaderDocument-1.5.0.*"
/usr/share/gir-1.0/XreaderDocument-1.5.0.gir
/usr/lib/x86_64-linux-gnu/girepository-1.0/XreaderDocument-1.5.0.typelib
```
hm ...

**Comment by wujastyk** [comment]
Me too, exactly:

$nemo-preview

(nemo-preview-start:2420): Cjs-WARNING **: JS ERROR: Error: Requiring
XreaderDocument, version none: Typelib file for namespace 'XreaderDocument'
(any version) not found
@/usr/share/nemo-preview/js/viewers/evince.js:28:7

Segmentation fault (core dumped)

**Comment by leigh123linux** [comment]
@mtwebster I think xreader typelib is to blame

```
$ g-ir-inspect --print-typelibs EvinceDocument
typelib: Gtk-3.0
typelib: Pango-1.0
typelib: GObject-2.0
typelib: xlib-2.0
typelib: cairo-1.0
typelib: Gdk-3.0
typelib: Gio-2.0
typelib: Atk-1.0
typelib: GdkPixbuf-2.0
typelib: GModule-2.0
typelib: GLib-2.0
$ g-ir-inspect --print-typelibs XreaderDocument
Failed to load typelib: Typelib file for namespace 'XreaderDocument' (any version) not found
```

**Comment by leigh123linux** [comment]
fixed in nemo-preview-3.6.2

https://github.com/linuxmint/nemo-extensions/commit/52767dc75260935fc4c6a62f1b94c8c3798e5110

**Comment by miloumeeloo** [comment]
I still have this error with 4.8.0:
(nemo-preview-start:351529): Cjs-CRITICAL **: 17:31:20.719: JS ERROR: GLib.Error g-invoke-error-quark: Could not locate ev_init: libxreaderdocument.so.3: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
_init@/usr/share/nemo-preview/js/viewers/xreader.js:48:9
XreaderRenderer@/usr/share/nemo-preview/js/viewers/xreader.js:43:10
@/usr/share/nemo-preview/js/viewers/xreader.js:181:16

~ ➜  find /usr -name "XreaderDocument*.*"
/usr/lib/x86_64-linux-gnu/girepository-1.0/XreaderDocument-1.5.typelib
/usr/share/gir-1.0/XreaderDocument-1.5.gir

~ ➜  g-ir-inspect --print-typelibs EvinceDocument
typelib: xlib-2.0
typelib: GLib-2.0
typelib: Gdk-3.0
typelib: GdkPixbuf-2.0
typelib: Gtk-3.0
typelib: cairo-1.0
typelib: GObject-2.0
typelib: Pango-1.0
typelib: Gio-2.0
typelib: GModule-2.0
typelib: Atk-1.0

~ ➜  g-ir-inspect --print-typelibs XreaderDocument
typelib: xlib-2.0
typelib: GLib-2.0
typelib: Gdk-3.0
typelib: GdkPixbuf-2.0
typelib: Gtk-3.0
typelib: cairo-1.0
typelib: GObject-2.0
typelib: Pango-1.0
typelib: Gio-2.0
typelib: GModule-2.0
typelib: Atk-1.0
